services:
  po-translator:
    build: .
    volumes:
      - ./translations:/app/translations
      - ./reports:/app/reports
    working_dir: /app
    stdin_open: true
    tty: true
    command: ["python", "-u", "localization-copy-tool.py"]
